---
subsystems:
- name: power
  system: serial_iec
  port: /dev/kaifa
- name: heat
  system: multical66
  port: /dev/kamstrup
  interval: 1800
- name: influx
  system: influxdb
  connection:
    host: influxdb.cloud.com
    port: 443
    ssl: True
    verify_ssl: True
    username: john
    password: PythonIsGreat
    database: pynuts
  tags:
    marco: polo
...
